---
title: 'Deskriptive Statistik'
author: 'Prof. Christoph Hanck'
author2: 'M.Sc. Jens Klenke'
subtitle: 'Übung 1'
semester: "Wintersemester 2022/2023"
output:
  pdf_document:
    keep_tex: yes
    template: ../template.tex
    fig_caption: yes
    number_sections: true
toc: true
lot: true
lof: true
graphics: true
linkcolor: black
urlcolor: black
citecolor: black
colorlinks: true
font: Times New Roman
fontsize: 12pt
geometry: lmargin = 2cm, rmargin = 2.5cm, tmargin = 2cm, bmargin = 2.5cm
classoption: a4paper
---

```{r , include=FALSE}
#Sys.setlocale(locale = "English_United States.1252") ## English US Windows
knitr::opts_chunk$set(echo = TRUE)

#options(kableExtra.latex.load_packages = FALSE)
#### required packages ####
source("../includes/packages/packages.R")
```


# Summen und Produkte

In dieser Aufgabe soll der Umgang mit Produkten und Summen, die in der Statistik sehr häufig verwendet werden, in Erinnerung gerufen werden.

\begin{enumerate}[label=(\alph*)]
  \item Gegeben sind:
    \begin{center}
      \begin{tabular}{l c c c c}
        \toprule
          $i$   & 1 & 2 & 3 & 4 \\ 
          \midrule
          $x_i$ & 6 & 4 & 1 & 3 \\
          $y_i$ & 1 & 3 & 4 & 2 \\
        \bottomrule
      \end{tabular}
    \end{center}


Berechnen Sie: $$\sum_{i=1}^4 x_i, \qquad \sum_{i=1}^4 x_iy_i, \qquad \prod_{i=1}^4 x_i, \qquad \prod_{i=1}^4 x_iy_i, \qquad \prod_{i=1}^4 x_i^2y_i^{0.5}$$.



\item Berechnen Sie möglichst einfach
  \begin{enumerate}[label=(\roman*)]
  \setlength\itemsep{10px}
    \item $\displaystyle \sum_{i=1}^{20} (6 - 4i) + \sum_{i=1}^{20} (2i + 2)$

    \item $\displaystyle \sum_{i=1}^{30} (i^2+2i-3) + \sum_{i=1}^{30} (3i^2+5i + 8)$

    \item $\displaystyle \sum_{i=1}^{40} (1+i)^2 + \sum_{i=1}^{40} (1-i)^2$
  \end{enumerate}
\vspace{0.5cm}

Beachten Sie dabei, dass gilt:
\begin{eqnarray*}
1+2+3+\ldots+n &=& \sum_{i=1}^n i = \frac{n(n+1)}{2}\\
1^2+2^2+3^2+\ldots+n^2 &=& \sum_{i=1}^n i^2 = \frac{n(n+1)(2n+1)}{6}\\
\end{eqnarray*}

\item Gegeben ist die folgende Matrix $B=(b_{ij})$; $i=1,\ldots,I$ ist der Zeilenindex und $j=1,\ldots,J$ ist der Spaltenindex: \\
\begin{center}
$B= \left(
  \begin{array}{cccccc}
1 & 4 & 4 & 7 & 8 & 4 \\
2 & 3 & 6 & 6 & 2 & 3 \\
6 & 9 & 7 & 6 & 7 & 2 \\
5 & 7 & 8 & 8 & 9 & 6 \\
4 & 6 & 2 & 3 & 4 & 5 \\
3 & 5 & 2 & 3 & 7 & 7 \\
\end{array}
\right)$
\end{center}
\end{enumerate}

Berechnen Sie: 

$$\sum_{i=1}^2\sum_{j=1}^3 b_{ij}, \quad \sum_{i=1}^2\sum_{j=1}^J b_{ij}, \quad \sum_{j=1}^J b_{2j}, \quad \sum_{i=1}^I\sum_{j=1}^2 b_{ij}, \quad \sum_{i=3}^4\sum_{j=5}^6 b_{ij}$$.

\vspace{.5cm}

# Merkmale

\begin{enumerate}[label=(\alph*)]
  \item Die Studierenden einer Universität verteilen sich wie folgt auf fünf Fakultäten:
  
  \begin{center}
    \begin{tabular}{lcccccr}
      \textbf{Fakultät}    & A   & B  & C   & D   & E   & $\sum\quad$ \\
        \midrule
      \textbf{Studierende} & 100 & 50 & 450 & 200 & 200 & $\quad$\textbf{1.000} \\
    \end{tabular}
  \end{center}
  
  

Geben Sie für die beiden Merkmale $M_1$: \textit{Fakultät} und $M_2$: \textit{Anzahl der Studierenden pro Fakultät} jeweils die Merkmalsausprägungen, die Merkmalsträger und die Klassifikation des Merkmals an.\\
\item Geben Sie bei den nachfolgenden Variablen an, welches Skalenniveau sie besitzen:\\
Geschlecht, Beruf, Warengruppe, Universitätsnoten, Einkommen, Vermögen.
\end{enumerate}
  
