project:
  type: website
  output-dir: "docs"

website:
  title: "EidÖ WiSe22"
  navbar:
    left:
      - href: index.qmd
        text: ""
  
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

