project:
  type: website

website:
  title: "EidÖ WiSe22"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

