project:
  type: website
  output-dir: "docs"

website:
  title: "DS WiSe 22"
  navbar:
    left:
      - href: Vorlesung.qmd
        text: "Vorlesung"
      - href: uebung.qmd
        text: "Übung"
  
format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

